### ISSUE TITLE
[Warn]: runlimit exhausted: runningpending job reason = 0 if system resumes from hibernation

### ISSUE THREAD

**Issue by hariseldon99** [fasrc/slurm_showq#13]
Hi,

I have a single node Ubuntu 20.04LTS cluster (slurm-wlm 19.05.5) that has to hibernate/resume outside business hours. This is accomplished by a cron job that runs the hibernate command.

Jobs that were running during hibernation are suspended before and restored after (via [this script](https://github.com/hariseldon99/buparamshavak/blob/main/shavak_root/usr/local/bin/slurm_cleanup.py) configged in '/etc/hibernate/common.conf'). 

If a job goes through this process, running "squeue" or
```bash
$ scontrol show job jobidXXX
```
after resume shows the job state properly (verified independently with top), but running showq yields

```bash
[Warn]: runlimit exhausted: runningpending job reason = 0
```
I suspect that this happens because of [line 206 of slurm_showq.cpp](https://github.com/fasrc/slurm_showq/blob/7d9bbdb18b2079c7320a24b779e6ebddd8d023d5/slurm_showq.cpp#L206), where the 'remain_time' is computed as the arithmetic difference between projected end time and current clock time. If this yields a negative number, then the conditional in [line 254 of slurm_showq.cpp](https://github.com/fasrc/slurm_showq/blob/7d9bbdb18b2079c7320a24b779e6ebddd8d023d5/slurm_showq.cpp#L254) is triggered with 'True', causing the error message to be printed.

This is a false positive, as it does not take into account suspend/resume times, which (AFAIK) slurm increments to walltime if the job was suspended/resumed via slurm ([the script](https://github.com/hariseldon99/buparamshavak/blob/main/shavak_root/usr/local/bin/slurm_cleanup.py) suspends all running jobs prior to hibernation, and resumes them post).

Can this be fixed?

Regards,
AR

**Comment by hariseldon99** [comment]
Um, not really much of a C++ guy, but I'll give it a shot.

I'm guessing that this "job_ptr" thingie has all the info about all the jobs, and [line 185](https://github.com/fasrc/slurm_showq/blob/master/slurm_showq.cpp#LL185C4-L185C7) in the loop thingie references a pointer to data for a particular job.

Would you please point me to the docs for the slurm development files where details for this data structure are given? It would save me the pain of globbing my way through a lot of source code.


AR

**Comment by pedmon** [comment]
Ah okay. We could also just nuke that warning as I'm not sure if its 
that terribly useful.  Slurm doesn't typically suffer from the error of 
time overruns.

So my feeling then is to just remove that warning as I don't think its 
useful.

-Paul Edmon-

**Comment by hariseldon99** [comment]
'kay, here's a diff

```cpp
254,258c254,259
< 	  if(hours_remain < 0 || mins_remain < 0 || secs_remain < 0)
< 	    {	 
< 	      printf("[Warn]: runlimit exhausted: runningpending job reason = %i\n",job->state_reason);
< 	      continue;
< 	    }
---
> 	   //Nuked!
> 	  //if(hours_remain < 0 || mins_remain < 0 || secs_remain < 0)
> 	    //{	 
> 	      //printf("[Warn]: runlimit exhausted: runningpending job reason = %i\n",job->state_reason);
> 	      //continue;
> 	    //}

```
Do I really have to fork it and put in a pull request, or could you just patch it?

**Comment by pedmon** [comment]
I will just patch it.  Give me a sec.

-Paul Edmon-

**Comment by pedmon** [comment]
Okay, patch is in place. Let me know if you have any other problems.

**Comment by hariseldon99** [comment]
Ok, I'll schedule a job overlapping with the next hibernation period and update.
